# Generated by Django 5.2.1 on 2025-07-04 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TurnoOEE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(unique=True)),
                ('cliente', models.CharField(max_length=100)),
                ('codigo', models.CharField(blank=True, max_length=20, null=True)),
                ('producto', models.CharField(max_length=100)),
                ('linea', models.CharField(max_length=50)),
                ('turno', models.CharField(max_length=20)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('tiempo_planeado', models.PositiveIntegerField(help_text='En minutos')),
                ('produccion_planeada', models.PositiveIntegerField(help_text='Producción planeada en unidades')),
                ('produccion_real', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResumenTurnoOee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.CharField(max_length=100)),
                ('codigo', models.CharField(blank=True, max_length=20, null=True)),
                ('producto', models.CharField(max_length=100)),
                ('tiempo_paro', models.PositiveIntegerField(help_text='Tiempo de paro en minutos')),
                ('tiempo_planeado', models.PositiveIntegerField(help_text='Tiempo planeado en minutos')),
                ('produccion_teorica', models.PositiveIntegerField(help_text='Producción teórica en unidades')),
                ('produccion_real', models.PositiveIntegerField(help_text='Producción real en unidades')),
                ('productos_malos', models.PositiveIntegerField(help_text='Cantidad de productos malos')),
                ('productos_buenos', models.PositiveIntegerField(help_text='Cantidad de productos buenos')),
                ('eficiencia', models.FloatField(help_text='Eficiencia del turno en porcentaje')),
                ('disponibilidad', models.FloatField(help_text='Disponibilidad del turno en porcentaje')),
                ('calidad', models.FloatField(help_text='Calidad del turno en porcentaje')),
                ('oee', models.FloatField(help_text='OEE del turno en porcentaje')),
                ('verificado', models.BooleanField(default=False)),
                ('verificado_por', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_de_verificacion', models.DateTimeField(blank=True, null=True)),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumenes_linea', to='calculo_oee.turnooee')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumenes_turno', to='calculo_oee.turnooee')),
            ],
        ),
        migrations.CreateModel(
            name='Reproceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=100)),
                ('cantidad', models.PositiveIntegerField()),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reprocesos', to='calculo_oee.turnooee')),
            ],
        ),
        migrations.CreateModel(
            name='Detencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=100)),
                ('duracion', models.PositiveIntegerField(help_text='Duración en minutos')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detenciones', to='calculo_oee.turnooee')),
            ],
        ),
    ]
