# Generated by Django 5.2.1 on 2025-07-14 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculo_oee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumenturnooee',
            name='linea',
            field=models.CharField(max_length=50),
        ),
    ]
