# Generated by Django 5.2.1 on 2025-07-14 23:27

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('calculo_oee', '0002_rename_turno_detencion_lote_and_more'),  # ajusta al último número
    ]

    operations = [
        migrations.AddField(
            model_name='detencion',
            name='comentarios',
            field=models.TextField(null=True, blank=True, max_length=200, help_text="Comentarios adicionales sobre la detención"),
        ),
    ]
