server {
    listen 80;
    server_name pgadmin.controldeprocesosquinta.com;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name pgadmin.controldeprocesosquinta.com;

    ssl_certificate /etc/letsencrypt/live/pgadmin.controldeprocesosquinta.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/pgadmin.controldeprocesosquinta.com/privkey.pem;

    location / {
        proxy_pass http://pgadmin:80;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Script-Name /;

        proxy_hide_header Content-Security-Policy;
        add_header Content-Security-Policy "default-src 'self' https: wss: data: blob: 'unsafe-inline' 'unsafe-eval';" always;
    }
}