# Generated by Django 4.2.4 on 2023-08-27 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosFormularioPcc2DetectorMetales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tecnologo', models.CharField(max_length=100)),
                ('fecha_registro', models.DateTimeField()),
                ('lote', models.IntegerField()),
                ('turno', models.TextField()),
                ('tipo_metal', models.TextField()),
                ('medicion', models.TextField()),
                ('producto', models.TextField()),
                ('observaciones', models.TextField()),
                ('accion_correctiva', models.IntegerField()),
            ],
        ),
    ]
