# Generated by Django 4.2.4 on 2023-08-29 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosFormularioTemperaturaDespachoJumbo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tecnologo', models.CharField(max_length=100)),
                ('fecha_registro', models.DateTimeField()),
                ('cadena', models.TextField()),
                ('item', models.TextField()),
                ('producto', models.TextField()),
                ('temperatura_producto', models.FloatField()),
                ('revision_etiquetado', models.TextField()),
                ('lote', models.TextField()),
                ('fecha_vencimiento', models.DateTimeField()),
                ('accion_correctiva', models.IntegerField()),
                ('verificacion_accion_correctiva', models.FloatField()),
            ],
        ),
    ]
