version: '3.8'

services:
  db:
    image: postgres
    volumes:
      - ./app/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: SCG_Quinta
      POSTGRES_USER: postgres
      #POSTGRES_PASSWORD: radcliffe # Para widows
      POSTGRES_PASSWORD: Dsal1212 # Para linux

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "diego.saldias.quijada@gmail.com"  # Cambia a tu email
      PGADMIN_DEFAULT_PASSWORD: "radcliffe"  # Cambia a tu contraseña
    ports:
      - "5050:80"  # pgAdmin estará disponible en el puerto 5050 de tu máquina host http://localhost:5050
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db

  web:
    build: .
    command: gunicorn SCG_Quinta.wsgi:application --bind 0.0.0.0:8000 --workers 10 --timeout 60
    volumes:
      - .:/code
    depends_on:
      - db
    environment:
      DATABASE_HOST: db

  nginx:
    image: nginx:1.19
    ports:
      - "80:80" # http://localhost:80/login  entrada a la aplicacion SCG_Quinta
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./staticfiles:/static
    depends_on:
      - web

volumes:
  pgdata:
  pgadmin: