version: '3.8'

services:
  db:
    image: postgres
    volumes:
      - ./app/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: SCG_Quinta
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Dsal1212

  web:
    build: .
    command: gunicorn SCG_Quinta.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:Dsal1212@db/SCG_Quinta

  nginx:
    image: nginx:1.19
    ports:
      - "80:80"
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./staticfiles:/static
      - ./mediafiles:/media
    depends_on:
      - web