# Generated by Django 4.2.4 on 2023-09-06 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosFormularioHistorialTermometro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tecnologo', models.CharField(max_length=100)),
                ('fecha_registro', models.DateTimeField()),
                ('codigo_termometro', models.TextField()),
                ('valor_1', models.FloatField()),
                ('valor_2', models.FloatField()),
                ('valor_3', models.FloatField()),
                ('valor_4', models.FloatField()),
                ('valor_5', models.FloatField()),
                ('promedio_prueba', models.FloatField()),
                ('valor_6', models.FloatField()),
                ('valor_7', models.FloatField()),
                ('valor_8', models.FloatField()),
                ('valor_9', models.FloatField()),
                ('valor_10', models.FloatField()),
                ('promedio_patron', models.FloatField()),
                ('factor_anual', models.FloatField()),
                ('promedio_termometros', models.FloatField()),
                ('nivel_aceptacion', models.FloatField()),
                ('cumplimiento', models.TextField()),
                ('accion_correctiva', models.IntegerField()),
                ('verificacion_accion_correctiva', models.TextField()),
            ],
        ),
    ]
