# Generated by Django 4.2.4 on 2023-09-26 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial_termometro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosformulariohistorialtermometro',
            name='accion_correctiva',
            field=models.TextField(),
        ),
    ]
