# Generated by Django 4.2.6 on 2023-11-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_de_transporte', '0002_datosformulariocontroldetransporte_fecha_de_verificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosformulariocontroldetransporte',
            name='verificado_por',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
