# Generated by Django 5.2.1 on 2025-07-04 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosFormularioControlDePesosInsumosKuchen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tecnologo', models.CharField(max_length=100)),
                ('fecha_registro', models.DateTimeField(unique=True)),
                ('cliente', models.TextField()),
                ('codigo_producto', models.CharField(blank=True, max_length=20, null=True)),
                ('producto', models.TextField()),
                ('peso_receta', models.IntegerField()),
                ('peso_real', models.IntegerField()),
                ('lote', models.TextField()),
                ('turno', models.TextField()),
                ('verificado', models.BooleanField(default=False)),
                ('verificado_por', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_de_verificacion', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
