# Generated by Django 4.2.4 on 2023-08-29 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosFormularioInformeDeIncidentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tecnologo', models.CharField(max_length=100)),
                ('fecha_registro', models.DateTimeField()),
                ('fuente_material', models.TextField()),
                ('cantidad_contaminada', models.TextField()),
                ('unidad_de_medida', models.TextField()),
                ('lote_producto_contaminado', models.TextField()),
                ('observaciones', models.TextField()),
                ('analisis_causa', models.TextField()),
                ('accion_correctiva', models.TextField()),
            ],
        ),
    ]
