# Generated by Django 4.2.4 on 2023-11-15 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informe_de_incidentes', '0002_datosformularioinformedeincidentes_fecha_de_verificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosformularioinformedeincidentes',
            name='cantidad_contaminada',
            field=models.FloatField(),
        ),
    ]
