# Generated by Django 4.2.4 on 2023-10-03 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosFormularioCrearCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.TextField()),
                ('perfil_usuario', models.TextField()),
                ('rut', models.TextField()),
                ('password', models.TextField()),
                ('new_password', models.TextField()),
            ],
        ),
    ]
