# Generated by Django 4.2.4 on 2023-10-15 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_datosformulariocrearcuenta_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosformulariocrearcuenta',
            name='perfil_usuario',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='datosformulariocrearcuenta',
            name='rut',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
