# Generated by Django 4.2.4 on 2023-10-15 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_datosformulariocrearcuenta_perfil_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosformulariocrearcuenta',
            name='nombre_completo',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='datosformulariocrearcuenta',
            name='rut',
            field=models.CharField(max_length=12),
        ),
    ]
