# Generated by Django 4.2.6 on 2023-11-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_datosformulariocrearcuenta_nombre_completo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosformulariocrearcuenta',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
