# Generated by Django 4.2.4 on 2025-05-31 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_datosformulariocrearcuenta_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosformulariocrearcuenta',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
