# Generated by Django 4.2.4 on 2025-05-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosFormularioControlDePesos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tecnologo', models.CharField(max_length=100)),
                ('fecha_registro', models.DateTimeField()),
                ('cliente', models.TextField()),
                ('producto', models.TextField()),
                ('peso_receta', models.FloatField()),
                ('peso_real', models.FloatField()),
                ('lote', models.TextField()),
                ('turno', models.TextField()),
                ('verificado', models.BooleanField(default=False)),
                ('verificado_por', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_de_verificacion', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
