# Generated by Django 4.2.4 on 2025-05-31 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_de_pesos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosformulariocontroldepesos',
            name='peso_real',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='datosformulariocontroldepesos',
            name='peso_receta',
            field=models.IntegerField(),
        ),
    ]
