# Generated by Django 5.2.1 on 2025-07-04 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_de_pesos', '0002_alter_datosformulariocontroldepesos_peso_real_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosformulariocontroldepesos',
            name='codigo_producto',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='datosformulariocontroldepesos',
            name='fecha_registro',
            field=models.DateTimeField(unique=True),
        ),
    ]
