"""
Django settings for SCG_Quinta project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--^2f**zyj9i4&tn2@ytw(rk7si&z0qum#($#4c87a3o$^1t*5r'

# SECURITY WARNING: don't run with debug turned on in production!   
DEBUG = False

ALLOWED_HOSTS = ['127.0.0.53','35.174.221.108','controldeprocesosquinta.com','www.controldeprocesosquinta.com']


# Application definition

LOCAL_APPS = [
    "inicio.apps.InicioConfig",
    "monitoreo_del_agua.apps.MonitoreoDelAguaConfig",
    "monitoreo_de_plagas.apps.MonitoreoDePlagasConfig",
    "pcc2_detector_metales.apps.Pcc2DetectorMetalesConfig",
    "recepcion_mpme.apps.RecepcionMpmeConfig",
    "higiene_y_conducta_personal.apps.HigieneYConductaPersonalConfig",
    "control_de_transporte.apps.ControlDeTransporteConfig",
    "temperatura_despacho_ptjumbo.apps.TemperaturaDespachoPtjumboConfig",
    "temperatura_despacho_ptsisa.apps.TemperaturaDespachoPtsisaConfig",
    "informe_de_incidentes.apps.InformeDeIncidentesConfig",
    "historial_termometro.apps.HistorialTermometroConfig",
    "control_material_extraño.apps.ControlMaterialExtrañoConfig",
    "rechazo_mp_in_me.apps.RechazoMpInMeConfig",
    "reclamo_a_proveedores.apps.ReclamoAProveedoresConfig",
    "selecciones.apps.SeleccionesConfig",
    "login.apps.LoginConfig",
    "control_de_pesos.apps.ControlDePesosConfig",
    "control_parametros_gorreri.apps.ControlParametrosGorreriConfig",
    "control_de_pesos_prelistos.apps.ControlDePesosPrelistosConfig",
    "control_de_pesos_insumos_kuchen.apps.ControlDePesosInsumosKuchenConfig",
    "calculo_oee.apps.CalculoOeeConfig",
    "control_parametros_bizcocho.apps.ControlParametrosBizcochoConfig"
]

DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

INSTALLED_APPS = LOCAL_APPS + DJANGO_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'SCG_Quinta.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'SCG_Quinta.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': BASE_DIR / 'db.sqlite3',
#    }
#}

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'SCG_Quinta',
        'USER': 'postgres',
        'PASSWORD': 'radcliffe', # Para Windows y AWS
        #'PASSWORD': 'Dsal1212', # Para Linux
        #'HOST': 'localhost',  # Para servidor desarrollo Django
        'HOST': 'db', # Para Docker
        'PORT': '5432',  # Puerto predeterminado de PostgreSQL.
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Chile/Continental'

USE_I18N = True 

USE_TZ = True 


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/' 

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': 'debug.log',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}

SESSION_ENGINE = 'django.contrib.sessions.backends.db'

AUTH_USER_MODEL = 'login.DatosFormularioCrearCuenta'

LOGIN_URL = '/login/' 

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760 # 10 MB