# Generated by Django 4.2.5 on 2023-09-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosFormularioReclamoProveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tecnologo', models.CharField(max_length=100)),
                ('fecha_registro', models.DateTimeField()),
                ('nombre_proveedor', models.TextField()),
                ('fecha_reclamo', models.DateTimeField()),
                ('nombre_del_producto', models.TextField()),
                ('fecha_elaboracion', models.DateTimeField()),
                ('lote', models.TextField()),
                ('fecha_vencimiento', models.DateTimeField()),
                ('no_conformidad', models.TextField()),
                ('clasificacion', models.TextField()),
                ('cantidad_involucrada', models.FloatField()),
                ('unidad_de_medida', models.TextField()),
                ('archivo_foto', models.BinaryField()),
            ],
        ),
    ]
