# Generated by Django 4.2.5 on 2023-09-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosFormularioRechazoMpInMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tecnologo', models.CharField(max_length=100)),
                ('fecha_registro', models.DateTimeField()),
                ('nombre_proveedor', models.TextField()),
                ('numero_factura', models.IntegerField()),
                ('nombre_transportista', models.TextField()),
                ('nombre_producto', models.TextField()),
                ('fecha_elaboracion', models.DateTimeField()),
                ('lote', models.TextField()),
                ('fecha_vencimiento', models.DateTimeField()),
                ('motivo_rechazo', models.TextField()),
                ('cantidad_producto_involucrado', models.FloatField()),
                ('unidad_de_medida', models.TextField()),
                ('clasificacion', models.TextField()),
            ],
        ),
    ]
