# Generated by Django 4.2.4 on 2023-11-15 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion_mpme', '0002_datosformulariorecepcionmpme_fecha_de_verificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosformulariorecepcionmpme',
            name='grados_brix',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='datosformulariorecepcionmpme',
            name='numero_factura',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='datosformulariorecepcionmpme',
            name='temperatura_producto',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='datosformulariorecepcionmpme',
            name='temperatura_transporte',
            field=models.IntegerField(),
        ),
    ]
