# Generated by Django 4.2.4 on 2023-11-23 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion_mpme', '0003_alter_datosformulariorecepcionmpme_grados_brix_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosformulariorecepcionmpme',
            name='grados_brix',
            field=models.TextField(),
        ),
    ]
