# Generated by Django 4.2.4 on 2023-11-23 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion_mpme', '0004_alter_datosformulariorecepcionmpme_grados_brix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosformulariorecepcionmpme',
            name='temperatura_producto',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='datosformulariorecepcionmpme',
            name='temperatura_transporte',
            field=models.TextField(),
        ),
    ]
