# Generated by Django 4.2.6 on 2023-12-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion_mpme', '0005_alter_datosformulariorecepcionmpme_temperatura_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosformulariorecepcionmpme',
            name='grados_brix',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datosformulariorecepcionmpme',
            name='temperatura_producto',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datosformulariorecepcionmpme',
            name='temperatura_transporte',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
