# Generated by Django 4.2.4 on 2023-09-06 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosFormularioControlMaterialExtraño',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tecnologo', models.CharField(max_length=100)),
                ('fecha_registro', models.DateTimeField()),
                ('turno', models.TextField()),
                ('area_material', models.TextField()),
                ('tipo_material', models.TextField()),
                ('accion_correctiva', models.IntegerField()),
                ('verificacion_accion_correctiva', models.TextField()),
                ('observaciones', models.TextField()),
            ],
        ),
    ]
