# Generated by Django 4.2.4 on 2023-08-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosFormularioMonitoreoDelAgua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tecnologo', models.CharField(max_length=100)),
                ('fecha_registro', models.DateTimeField()),
                ('turno_mda', models.TextField()),
                ('planta_mda', models.TextField()),
                ('numero_llave', models.IntegerField()),
                ('punto_muestreo', models.TextField()),
                ('sabor_insipido', models.TextField()),
                ('olor_inodora', models.TextField()),
                ('color_incoloro', models.TextField()),
                ('ph_mda', models.FloatField()),
                ('cloro_libre', models.FloatField()),
                ('accion_correctiva', models.TextField()),
                ('resultado_ac', models.IntegerField()),
            ],
        ),
    ]
