# Generated by Django 4.2.4 on 2023-09-26 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo_del_agua', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosformulariomonitoreodelagua',
            name='resultado_ac',
            field=models.TextField(),
        ),
    ]
