# Generated by Django 4.2.4 on 2023-09-26 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo_del_agua', '0002_alter_datosformulariomonitoreodelagua_resultado_ac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosformulariomonitoreodelagua',
            name='numero_llave',
            field=models.TextField(),
        ),
    ]
