# Generated by Django 4.2.4 on 2023-11-15 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo_del_agua', '0004_datosformulariomonitoreodelagua_fecha_de_verificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosformulariomonitoreodelagua',
            name='accion_correctiva',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='datosformulariomonitoreodelagua',
            name='numero_llave',
            field=models.IntegerField(),
        ),
    ]
