# Generated by Django 4.2.4 on 2023-08-27 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosFormularioMonitoreoDePlagas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tecnologo', models.CharField(max_length=100)),
                ('fecha_registro', models.DateTimeField()),
                ('numero_estacion', models.IntegerField()),
                ('tipo_plaga', models.TextField()),
                ('tipo_trampa', models.TextField()),
                ('ubicacion', models.TextField()),
                ('monitoreo', models.TextField()),
                ('accion_correctiva', models.IntegerField()),
            ],
        ),
    ]
